In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv("C:/Users/Acer/Desktop/kaggle competitions/House prices - advanced regression/train.csv")

In [3]:
test = pd.read_csv("C:/Users/Acer/Desktop/kaggle competitions/House prices - advanced regression/test.csv")

In [4]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [6]:
train.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [7]:
train.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

## Approach 1: Using only the continuous variables and checking their regression coefficients

In [8]:
train['SalePrice'].dtype

dtype('int64')

In [9]:
train1 = train.select_dtypes(include = ['float64', 'int64'])
test1 = test.select_dtypes(include = ['float64', 'int64'])

In [10]:
len(train1.columns)

38

#### I will check which variables matter and which are useless data.

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
train1.columns

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold', 'SalePrice'],
      dtype='object')

In [13]:
train2 = train1.dropna()

In [14]:
X = train2.drop('SalePrice', axis =1)
y = train2['SalePrice']

In [15]:
X.head(2)

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,548,0,61,0,0,0,0,0,2,2008
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,460,298,0,0,0,0,0,0,5,2007

In [16]:
y.head(2)

0    208500
1    181500
Name: SalePrice, dtype: int64

In [17]:
X.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
count,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,...,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000,1121.000000
mean,726.842105,56.146298,70.665477,10122.956289,6.212310,5.561106,1972.264942,1985.683318,108.487957,438.399643,...,502.955397,92.610169,46.130241,21.844781,3.348796,16.100803,2.934880,23.429081,6.339875,2007.795718
std,420.769012,41.772684,24.266812,8129.302641,1.380822,1.068236,30.967730,21.025974,189.500966,468.385038,...,191.243043,121.868623,64.390029,61.282083,29.772540,57.801829,40.222087,165.759816,2.687854,1.335043
min,1.000000,20.000000,21.000000,1300.000000,2.000000,2.000000,1880.000000,1950.000000,0.000000,0.000000,...,160.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000
25%,364.000000,20.000000,60.000000,7590.000000,5.000000,5.000000,1953.000000,1966.000000,0.000000,0.000000,...,360.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000
50%,725.000000,50.000000,70.000000,9416.000000,6.000000,5.000000,1974.000000,1995.000000,0.000000,374.000000,...,484.000000,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000
75%,1091.000000,70.000000,80.000000,11361.000000,7.000000,6.000000,2003.000000,2005.000000,170.000000,702.000000,...,600.000000,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,1418.000000,857.000000,547.000000,552.000000,508.000000,480.000000,648.000000,2500.000000,12.000000,2010.000000

In [18]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

##### Now checking for the variable coefficients

In [19]:
coefficients = model.coef_
features = X.columns

print("Regression Coefficients:\n")
for i, name in enumerate(features):
    print(f"- {name}: {coefficients[i]:.4f}")  # Format coefficients with 4 decimal places

Regression Coefficients:

- Id: -1.2053
- MSSubClass: -200.0623
- LotFrontage: -116.0282
- LotArea: 0.5422
- OverallQual: 18656.2497
- OverallCond: 5239.4864
- YearBuilt: 316.4201
- YearRemodAdd: 119.4141
- MasVnrArea: 31.4076
- BsmtFinSF1: 9.6803
- BsmtFinSF2: 0.6662
- BsmtUnfSF: -2.6710
- TotalBsmtSF: 7.6755
- 1stFlrSF: 14.4718
- 2ndFlrSF: 15.1237
- LowQualFinSF: 1.9062
- GrLivArea: 31.5017
- BsmtFullBath: 9042.8022
- BsmtHalfBath: 2465.0370
- FullBath: 5433.1446
- HalfBath: -1098.3395
- BedroomAbvGr: -10218.9105
- KitchenAbvGr: -22023.4840
- TotRmsAbvGrd: 5464.1204
- Fireplaces: 4371.8698
- GarageYrBlt: -47.2763
- GarageCars: 16849.7172
- GarageArea: 6.2744
- WoodDeckSF: 21.4407
- OpenPorchSF: -2.2524
- EnclosedPorch: 7.2949
- 3SsnPorch: 33.4852
- ScreenPorch: 58.0465
- PoolArea: -60.5171
- MiscVal: -3.7615
- MoSold: -221.6980
- YrSold: -247.4485

### checking with p value - less than 0.05 is fine

In [20]:
import statsmodels.api as sm
model = sm.OLS(y,X).fit()

In [21]:
print(model.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:              SalePrice   R-squared (uncentered):                   0.968
Model:                            OLS   Adj. R-squared (uncentered):              0.967
Method:                 Least Squares   F-statistic:                              946.5
Date:                Tue, 19 Mar 2024   Prob (F-statistic):                        0.00
Time:                        19:32:33   Log-Likelihood:                         -13358.
No. Observations:                1121   AIC:                                  2.679e+04
Df Residuals:                    1086   BIC:                                  2.696e+04
Df Model:                          35
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Id               -1.1973      2.657     -0.451      0.652      -6.410       4.016
MSSubClass     -200.1887     34.490     -5.804      0.000    -267.863    -132.514
LotFrontage    -115.5376     61.186     -1.888      0.059    -235.594       4.519
LotArea           0.5414      0.157      3.439      0.001       0.233       0.850
OverallQual    1.867e+04   1478.437     12.630      0.000    1.58e+04    2.16e+04
OverallCond    5239.6093   1367.247      3.832      0.000    2556.864    7922.354
YearBuilt       315.4475     87.485      3.606      0.000     143.789     487.106
YearRemodAdd    119.3947     86.644      1.378      0.168     -50.613     289.402
MasVnrArea       31.4012      7.019      4.474      0.000      17.629      45.173
BsmtFinSF1        9.6641      3.126      3.091      0.002       3.530      15.799
BsmtFinSF2        0.6956      5.582      0.125      0.901     -10.257      11.649
BsmtUnfSF        -2.6795      2.935     -0.913      0.361      -8.438       3.080
TotalBsmtSF       7.6802      4.221      1.820      0.069      -0.602      15.962
1stFlrSF         14.4955      8.478      1.710      0.088      -2.141      31.132
2ndFlrSF         15.1348      7.709      1.963      0.050       0.008      30.262
LowQualFinSF      1.8419     20.935      0.088      0.930     -39.235      42.919
GrLivArea        31.4721      7.762      4.055      0.000      16.242      46.702
BsmtFullBath   9079.1386   3191.332      2.845      0.005    2817.264    1.53e+04
BsmtHalfBath   2434.2080   5068.455      0.480      0.631   -7510.865    1.24e+04
FullBath       5482.0331   3520.822      1.557      0.120   -1426.350    1.24e+04
HalfBath      -1072.4533   3317.313     -0.323      0.747   -7581.522    5436.615
BedroomAbvGr  -1.023e+04   2153.656     -4.749      0.000   -1.45e+04   -6001.573
KitchenAbvGr  -2.198e+04   6703.259     -3.279      0.001   -3.51e+04   -8826.738
TotRmsAbvGrd   5456.0284   1486.063      3.671      0.000    2540.149    8371.908
Fireplaces     4358.0056   2186.566      1.993      0.047      67.633    8648.379
GarageYrBlt     -47.5369     91.010     -0.522      0.602    -226.112     131.038
GarageCars     1.683e+04   3486.816      4.825      0.000    9983.548    2.37e+04
GarageArea        6.3290     12.119      0.522      0.602     -17.450      30.108
WoodDeckSF       21.5000     10.015      2.147      0.032       1.849      41.151
OpenPorchSF      -2.4418     19.453     -0.126      0.900     -40.612      35.729
EnclosedPorch     7.1465     20.598      0.347      0.729     -33.271      47.564
3SsnPorch        33.6385     37.560      0.896      0.371     -40.060     107.336
ScreenPorch      58.0373     20.398      2.845      0.005      18.014      98.061
PoolArea        -60.9430     29.807     -2.045      0.041    -119.428      -2.458
MiscVal          -3.6995      6.950     -0.532      0.595     -17.337       9.938
MoSold         -234.9081    417.320     -0.563      0.574   -1053.753     583.937
YrSold         -413.1413     87.020     -4.748      0.000    -583.888    -242.394
==============================================================================
Omnibus:                      433.527   Durbin-Watson:                   1.941
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            64918.659
Skew:                          -0.668   Prob(JB):                         0.00
Kurtosis:                      40.257   Cond. No.                     1.43e+16
==============================================================================

Notes:
[1] RÂ² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The smallest eigenvalue is 1.01e-21. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [22]:
coefficients = model.params
p_values = model.pvalues
## significant coefficients
sig_coefs = [(name, coef) for name, coef, p_value in zip(X.columns, coefficients, p_values) if p_value <=0.05]

In [23]:
sig_coefs

[('MSSubClass', -200.18873578909182),
 ('LotArea', 0.541359894788787),
 ('OverallQual', 18673.286299666514),
 ('OverallCond', 5239.609261533362),
 ('YearBuilt', 315.44754929610093),
 ('MasVnrArea', 31.401154102352862),
 ('BsmtFinSF1', 9.664106881039746),
 ('2ndFlrSF', 15.134780930543922),
 ('GrLivArea', 31.472140162088916),
 ('BsmtFullBath', 9079.13864041409),
 ('BedroomAbvGr', -10227.370374001657),
 ('KitchenAbvGr', -21979.543877405435),
 ('TotRmsAbvGrd', 5456.028363752977),
 ('Fireplaces', 4358.005579832191),
 ('GarageCars', 16825.20626703123),
 ('WoodDeckSF', 21.500006176536154),
 ('ScreenPorch', 58.0372766607516),
 ('PoolArea', -60.943040803400834),
 ('YrSold', -413.14129783204737)]

In [24]:
cols = ["Variable", "Coefficient"]

In [25]:
VC = pd.DataFrame(sig_coefs, columns = cols)     ### VC for variable and coefficient

In [26]:
VC

        Variable   Coefficient
0     MSSubClass   -200.188736
1        LotArea      0.541360
2    OverallQual  18673.286300
3    OverallCond   5239.609262
4      YearBuilt    315.447549
5     MasVnrArea     31.401154
6     BsmtFinSF1      9.664107
7       2ndFlrSF     15.134781
8      GrLivArea     31.472140
9   BsmtFullBath   9079.138640
10  BedroomAbvGr -10227.370374
11  KitchenAbvGr -21979.543877
12  TotRmsAbvGrd   5456.028364
13    Fireplaces   4358.005580
14    GarageCars  16825.206267
15    WoodDeckSF     21.500006
16   ScreenPorch     58.037277
17      PoolArea    -60.943041
18        YrSold   -413.141298

In [27]:
list1 = VC['Variable']
print(list1)

0       MSSubClass
1          LotArea
2      OverallQual
3      OverallCond
4        YearBuilt
5       MasVnrArea
6       BsmtFinSF1
7         2ndFlrSF
8        GrLivArea
9     BsmtFullBath
10    BedroomAbvGr
11    KitchenAbvGr
12    TotRmsAbvGrd
13      Fireplaces
14      GarageCars
15      WoodDeckSF
16     ScreenPorch
17        PoolArea
18          YrSold
Name: Variable, dtype: object

In [28]:
X2 = X[list1]

In [29]:
X2.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,MasVnrArea,BsmtFinSF1,2ndFlrSF,GrLivArea,BsmtFullBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,WoodDeckSF,ScreenPorch,PoolArea,YrSold
0,60,8450,7,5,2003,196.0,706,854,1710,1,3,1,8,0,2,0,0,0,2008
1,20,9600,6,8,1976,0.0,978,0,1262,0,3,1,6,1,2,298,0,0,2007
2,60,11250,7,5,2001,162.0,486,866,1786,1,3,1,6,1,2,0,0,0,2008
3,70,9550,7,5,1915,0.0,216,756,1717,1,3,1,7,1,3,0,0,0,2006
4,60,14260,8,5,2000,350.0,655,1053,2198,1,4,1,9,1,3,192,0,0,2008

### Now this X2 has only the numerical variables that matter - let's use this to make a regression model

In [30]:
model = LinearRegression()
model.fit(X2, y)

LinearRegression()

In [31]:
test.head(2) ### this also needs to be changed

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal

In [32]:
test2 = test[list1]

In [33]:
test2.describe() ### missing value imputation required

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,MasVnrArea,BsmtFinSF1,2ndFlrSF,GrLivArea,BsmtFullBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageCars,WoodDeckSF,ScreenPorch,PoolArea,YrSold
count,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1444.000000,1458.000000,1459.000000,1459.000000,1457.000000,1459.000000,1459.000000,1459.000000,1459.00000,1458.000000,1459.000000,1459.000000,1459.000000,1459.000000
mean,57.378341,9819.161069,6.078821,5.553804,1971.357779,100.709141,439.203704,325.967786,1486.045922,0.434454,2.854010,1.042495,6.385195,0.58122,1.766118,93.174777,17.064428,1.744345,2007.769705
std,42.746880,4955.517327,1.436812,1.113740,30.390071,177.625900,455.268042,420.610226,485.566099,0.530648,0.829788,0.208472,1.508895,0.64742,0.775945,127.744882,56.609763,30.491646,1.301740
min,20.000000,1470.000000,1.000000,1.000000,1879.000000,0.000000,0.000000,0.000000,407.000000,0.000000,0.000000,0.000000,3.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2006.000000
25%,20.000000,7391.000000,5.000000,5.000000,1953.000000,0.000000,0.000000,0.000000,1117.500000,0.000000,2.000000,1.000000,5.000000,0.00000,1.000000,0.000000,0.000000,0.000000,2007.000000
50%,50.000000,9399.000000,6.000000,5.000000,1973.000000,0.000000,350.500000,0.000000,1432.000000,0.000000,3.000000,1.000000,6.000000,0.00000,2.000000,0.000000,0.000000,0.000000,2008.000000
75%,70.000000,11517.500000,7.000000,6.000000,2001.000000,164.000000,753.500000,676.000000,1721.000000,1.000000,3.000000,1.000000,7.000000,1.00000,2.000000,168.000000,0.000000,0.000000,2009.000000
max,190.000000,56600.000000,10.000000,9.000000,2010.000000,1290.000000,4010.000000,1862.000000,5095.000000,3.000000,6.000000,2.000000,15.000000,4.00000,5.000000,1424.000000,576.000000,800.000000,2010.000000

In [34]:
test3 = test2.fillna(test2.mean())    ### test 3 is the data that I am gonna use

In [35]:
y_pred = model.predict(test3)

In [36]:
from sklearn.metrics import r2_score         ### r2
from sklearn.metrics import mean_absolute_error   #### MAE

In [37]:
#### Oh wait, what do I test it against? 
y_train_pred = model.predict(X2)

In [38]:
mean_absolute_error(y_train_pred, y)

22092.299341199123

In [39]:
r2_score(y_train_pred, y)

0.7611577033351091

# Prediction 1
### 1. I used statsmodels to see which variables out of the numerical ones actually matter. 
### 2. I used a linear regression model using only those variables. 
### This is my first prediction.

In [40]:
y_pred

array([119516.72740226, 164438.75581247, 171649.8403478 , ...,
       176487.73445368,  84177.9338383 , 261583.70127747])

In [41]:
y_pred_df = pd.DataFrame({"Predicted y": y_pred})

In [42]:
y_pred_df.to_csv('HousePricePrediction1.csv', index = False)

In [43]:
import os

# Get the current working directory
cwd = os.getcwd()

# Print the path
print("Current working directory:", cwd)

Current working directory: C:\Users\Acer

In [44]:
## this is where the csv gets saved

# Method 2
## I will use the same data but use some other model
### I will use Support Vector Machines

In [45]:
from sklearn.svm import SVR
# Create and train the SVR model
model = SVR(kernel='linear', C=100, epsilon=0.1)  # Adjust hyperparameters as needed
model.fit(X2, y)

SVR(C=100, kernel='linear')

In [47]:
## this is taking a lot of time I will proceed anyway
y_pred = model.predict(test3)
print(y_pred)

[127822.81631927 184775.50374297 196204.87944488 ... 189110.85005645
 117144.03479461 239112.5349472 ]

In [48]:
y_pred_df = pd.DataFrame({"Predicted y": y_pred})
y_pred_df.to_csv('HousePricePrediction2.csv', index = False)

In [50]:
r2_score(model.predict(X2), y)          ### not that bad, but Multiple Linear Regression was better

0.6794013775780694

# Method 3

### Now I will use the important categorical variables as well.
##### Method 2 gave a pretty bad result, by the way.